# **Multiple Variable Linear Regression**

In [272]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)

- Features and targets


In [273]:
x_train=np.array([[2104,5,1,45],[1416,3,2,40],[852,2,1,35]])
y_train=np.array([460,232,178])

print(f"x_train shape: {x_train.shape} , x_train data type: {x_train.dtype}")
print(x_train)
print(f"y_train shape: {y_train.shape} , y_train data type: {y_train.dtype}")
print(y_train)

x_train shape: (3, 4) , x_train data type: int32
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y_train shape: (3,) , y_train data type: int32
[460 232 178]


- initializing w,b with values near the optimum ones

In [274]:
b_in = 785.1811367994083
w_in = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_initial shape: {w_in.shape}, b_initial type: {type(b_in)}")

w_initial shape: (4,), b_initial type: <class 'float'>


- Prediction with element by element


In [275]:
def single_element_prediction(x,w,b):
    n=x.shape[0]
    out=0
    for i in range(n):
        out=out+w[i]*x[i]
    out=out+b
    return out

x=x_train[0,:]
single_element_prediction_result=single_element_prediction(x,w_in,b_in)
print(x)
print(single_element_prediction_result)
        

[2104    5    1   45]
459.9999976194083


- Single prediction with vectorization

In [276]:
def single_prediction_vector(x,w,b):
    return np.dot(x,w)+b

x=x_train[0,:]
single_prediction_vector_result=single_prediction_vector(x,w_in,b_in)
print(x)
print(single_prediction_vector_result)

[2104    5    1   45]
459.99999761940825


- Compute cost function

In [277]:
def compute_cost(x,y,w,b):
    n=y.shape[0]
    cost=0
    for i in range(n):
        cost=cost+(np.dot(w,x[i])+b-y[i])**2
    cost=cost/(2*n)
    return cost

cost=compute_cost(x_train,y_train,w_in,b_in)
print(cost)

1.5578904880036537e-12


- Compute Gradient

In [278]:
def compute_gradient(w,b,x,y):
    num=w.shape[0]
    m=y.shape[0]
    dj_dw=np.zeros(num)
    dj_db=0
    for i in range(m):
        f=np.dot(x[i],w)+b-y[i]
        for j in range(num):
            dj_dw[j]+=(f)*x[i][j]
        dj_db+=(f)
    dj_dw=dj_dw*(1/m)
    dj_db=dj_db*(1/m)
    return dj_dw,dj_db
        
        
#test
tmp_dj_dw, tmp_dj_db = compute_gradient( w_in, b_in,x_train, y_train)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: -1.673925169143331e-06
dj_dw at initial w,b: 
 [-2.73e-03 -6.27e-06 -2.22e-06 -6.92e-05]


- Computing gradient descent with multiple variables

In [279]:
def compute_descent(w_in,b_in,x,y,alpha,compute_cost,compute_gradient,num_iters):
    
    J_history=[]
    w=copy.deepcopy(w_in)
    b=b_in
    for i in range(num_iters):
        dj_dw , dj_db=compute_gradient(w,b,x,y)
        w=w-(alpha*dj_dw)
        b=b-alpha*dj_db
        if i<100000:
            J_history.append(compute_cost(x,y,w,b))
        if i% math.ceil(num_iters / 10) == 0:
            print(f"Iteration {i:4d}: Cost {J_history[-1]:8.2f}   ")
    return w,b,J_history


#test

initial_w = np.zeros_like(w_in)
initial_b = 0.
iter = 1000
alpha = 5.0e-7
w_final, b_final, J_hist = compute_descent(initial_w,initial_b,x_train, y_train,alpha,
                                                    compute_cost, compute_gradient, 
                                                    iter)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
num,_ = x_train.shape
for i in range(num):
    print(f"prediction: {np.dot(x_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")
            
        
    

Iteration    0: Cost  2529.46   
Iteration  100: Cost   695.99   
Iteration  200: Cost   694.92   
Iteration  300: Cost   693.86   
Iteration  400: Cost   692.81   
Iteration  500: Cost   691.77   
Iteration  600: Cost   690.73   
Iteration  700: Cost   689.71   
Iteration  800: Cost   688.70   
Iteration  900: Cost   687.69   
b,w found by gradient descent: -0.00,[ 0.2   0.   -0.01 -0.07] 
prediction: 426.19, target value: 460
prediction: 286.17, target value: 232
prediction: 171.47, target value: 178
