# **Multiple Variable Linear Regression**

In [8]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)

- Features and targets


In [9]:
x_train=np.array([[2104,5,1,45],[1416,3,2,40],[852,2,1,35]])
y_train=np.array([460,232,178])

print(f"x_train shape: {x_train.shape} , x_train data type: {x_train.dtype}")
print(x_train)
print(f"y_train shape: {y_train.shape} , y_train data type: {y_train.dtype}")
print(y_train)

x_train shape: (3, 4) , x_train data type: int32
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y_train shape: (3,) , y_train data type: int32
[460 232 178]


- initializing w,b with values near the optimum ones

In [10]:
b_in = 785.1811367994083
w_in = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_initial shape: {w_in.shape}, b_initial type: {type(b_in)}")

w_initial shape: (4,), b_initial type: <class 'float'>


- Prediction with element by element


In [11]:
def single_element_prediction(x,w,b):
    n=x.shape[0]
    out=0
    for i in range(n):
        out=out+w[i]*x[i]
    out=out+b
    return out

x=x_train[0,:]
single_element_prediction_result=single_element_prediction(x,w_in,b_in)
print(x)
print(single_element_prediction_result)
        

[2104    5    1   45]
459.9999976194083


- Single prediction with vectorization

In [12]:
def single_prediction_vector(x,w,b):
    return np.dot(x,w)+b

x=x_train[0,:]
single_prediction_vector_result=single_prediction_vector(x,w_in,b_in)
print(x)
print(single_prediction_vector_result)

[2104    5    1   45]
459.99999761940825


- Compute cost function

In [14]:
def compute_cost(x,y,w,b):
    n=y.shape[0]
    cost=0
    for i in range(n):
        cost=cost+(np.dot(w,x[i])+b-y[i])**2
    cost=cost/(2*n)
    return cost

cost=compute_cost(x_train,y_train,w_in,b_in)
print(cost)

1.5578904880036537e-12
